# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 18:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Atendente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('nome', models.CharField(max_length=80)),
                ('sobrenome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=16)),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_bairro', models.CharField(max_length=200, verbose_name='Nome do bairro')),
            ],
            options={
                'verbose_name': 'Bairro',
                'verbose_name_plural': 'Bairros',
                'ordering': ('nome_bairro',),
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Cargos',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cidade', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
                'ordering': ('nome_cidade',),
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do documento')),
                ('num_processo', models.CharField(max_length=12, verbose_name='Número do processo')),
                ('end_obra', models.CharField(max_length=150, verbose_name='Endereço da obra')),
                ('num_residencia', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área do terreno')),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Área construída')),
                ('observacao', models.TextField(blank=True, verbose_name='Observações')),
                ('data_documento', models.DateField(verbose_name='Data do documento')),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Requerente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='C.P.F')),
                ('telefone', models.CharField(max_length=15, verbose_name='Telefone')),
                ('endereco', models.CharField(max_length=150, verbose_name='Endereço')),
                ('num_residencia', models.CharField(max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=150, null=True)),
                ('cep', models.CharField(blank=True, max_length=9, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('bairro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro')),
            ],
            options={
                'verbose_name': 'Requerente',
                'verbose_name_plural': 'Requerentes',
            },
        ),
        migrations.CreateModel(
            name='ResponsavelTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Cargo', verbose_name='Cargo')),
            ],
            options={
                'verbose_name': 'Responsável Técnico',
                'verbose_name_plural': 'Responsáveis Técnicos',
                'ordering': ('nome',),
            },
        ),
        migrations.CreateModel(
            name='AlvaraConstrucao',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Documento')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número do documento')),
            ],
            options={
                'verbose_name': 'Alvará de Construção',
                'verbose_name_plural': 'Alvarás de Construção',
                'ordering': ('numero', 'ano'),
            },
            bases=('core.documento',),
        ),
        migrations.CreateModel(
            name='AutoRegularizacao',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Documento')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número do documento')),
            ],
            options={
                'verbose_name': 'Auto de Regularização',
                'verbose_name_plural': 'Autos de Regularização',
            },
            bases=('core.documento',),
        ),
        migrations.CreateModel(
            name='HabiteSe',
            fields=[
                ('documento_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Documento')),
                ('numero', models.PositiveIntegerField(unique=True, verbose_name='Número do documento')),
                ('alvara', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AlvaraConstrucao', verbose_name='Alvará')),
                ('auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AutoRegularizacao', verbose_name='Auto')),
            ],
            options={
                'verbose_name': 'Habite-se',
                'verbose_name_plural': 'Habite-ses',
            },
            bases=('core.documento',),
        ),
        migrations.AddField(
            model_name='documento',
            name='bairro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AddField(
            model_name='documento',
            name='requerente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Requerente', verbose_name='Requerente'),
        ),
        migrations.AddField(
            model_name='documento',
            name='resp_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ResponsavelTecnico', verbose_name='Responsável técnico'),
        ),
        migrations.AddField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cidade', to='core.Cidade', verbose_name='Cidade'),
        ),
    ]
