# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-10 20:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atendente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='senha',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='atendente',
            name='username',
        ),
        migrations.AlterField(
            model_name='atendente',
            name='matricula',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atendente', to=settings.AUTH_USER_MODEL),
        ),
    ]
