# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 08:58
from __future__ import unicode_literals

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_auto_20170910_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendente',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alvaraconstrucao',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número do documento', unique=True, validators=[core.models.valida_num], verbose_name='Número do documento'),
        ),
        migrations.AlterField(
            model_name='atendente',
            name='matricula',
            field=models.CharField(help_text='Matrícula do atendente', max_length=10),
        ),
        migrations.AlterField(
            model_name='autoregularizacao',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número do documento', unique=True, validators=[core.models.valida_num], verbose_name='Número do documento'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='cidade',
            field=models.ForeignKey(help_text='Cidade em que o bairro pertence', on_delete=django.db.models.deletion.CASCADE, related_name='cidade', to='core.Cidade', verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='bairro',
            name='nome_bairro',
            field=models.CharField(help_text='Nome do bairro', max_length=200, verbose_name='Nome do bairro'),
        ),
        migrations.AlterField(
            model_name='cargo',
            name='descricao',
            field=models.CharField(help_text='Descrição do cargo', max_length=100, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='estado',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], help_text='Informa o estado em que a cidade pertence', max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome_cidade',
            field=models.CharField(help_text='Informe o nome da cidade', max_length=100, verbose_name='Nome da cidade'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='ano',
            field=models.PositiveIntegerField(help_text='Ano do documento a partir de 2013', validators=[core.models.valida_ano], verbose_name='Ano do documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='area_construida',
            field=models.DecimalField(decimal_places=2, help_text='Área construída no formato: 000.00', max_digits=10, verbose_name='Área construída'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='area_terreno',
            field=models.DecimalField(decimal_places=2, help_text='Área do terreno no formato: 000.00', max_digits=10, verbose_name='Área do terreno'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='bairro',
            field=models.ForeignKey(help_text='Bairro', on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='cep',
            field=models.CharField(blank=True, help_text='Cep no formato 00000-000', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='complemento',
            field=models.CharField(blank=True, help_text='Senão possuir complemento deixe em branco', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do cadastro'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='data_documento',
            field=models.DateField(help_text='Data em que o documento foi assinado. YYYY-MM-DD', verbose_name='Data do documento'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='end_obra',
            field=models.CharField(help_text='Endereço da obra', max_length=150, verbose_name='Endereço da obra'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='num_processo',
            field=models.CharField(help_text='Número do processo no formato: 00.0000/0000', max_length=12, verbose_name='Número do processo'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='num_residencia',
            field=models.CharField(help_text='Número do endereço, se não possuir insira "S/N"', max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='observacao',
            field=models.TextField(blank=True, help_text='Senão possuir observações deixe em branco', verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='requerente',
            field=models.ForeignKey(help_text='Requerente do documento', on_delete=django.db.models.deletion.CASCADE, to='core.Requerente', verbose_name='Requerente'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='resp_tecnico',
            field=models.ForeignKey(help_text='Responsável Técnico', on_delete=django.db.models.deletion.CASCADE, to='core.ResponsavelTecnico', verbose_name='Responsável técnico'),
        ),
        migrations.AlterField(
            model_name='habitese',
            name='alvara',
            field=models.ForeignKey(blank=True, help_text='Alvará associado, senão possuir deixe em branco', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AlvaraConstrucao', verbose_name='Alvará'),
        ),
        migrations.AlterField(
            model_name='habitese',
            name='auto',
            field=models.ForeignKey(blank=True, help_text='Auto associado, senão possuir deixe em branco', null=True, on_delete=django.db.models.deletion.CASCADE, to='core.AutoRegularizacao', verbose_name='Auto'),
        ),
        migrations.AlterField(
            model_name='habitese',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número do documento', unique=True, validators=[core.models.valida_num], verbose_name='Número do documento'),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='bairro',
            field=models.ForeignKey(help_text='Bairro', on_delete=django.db.models.deletion.CASCADE, to='core.Bairro', verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='cep',
            field=models.CharField(blank=True, help_text='Cep no formato 00000-000', max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='complemento',
            field=models.CharField(blank=True, help_text='Senão possuir complemento deixe em branco', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='cpf',
            field=models.CharField(help_text='C.P.F no formato: 000.000.000-00', max_length=14, unique=True, verbose_name='C.P.F'),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Data e hora do cadastro'),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='endereco',
            field=models.CharField(help_text='Nome do logradouro', max_length=150, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='nome',
            field=models.CharField(help_text='Nome completo do requerente', max_length=150, verbose_name='Nome do requerente'),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='num_residencia',
            field=models.CharField(help_text='Número da casa, se não possuir insira "S/N"', max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='requerente',
            name='telefone',
            field=models.CharField(help_text='Telefone Ex.: (00) 9 0000-0000 / (00) 0000-0000', max_length=16, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='responsaveltecnico',
            name='cargo',
            field=models.ForeignKey(help_text='Cargo do responsável técnico', on_delete=django.db.models.deletion.CASCADE, to='core.Cargo', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='responsaveltecnico',
            name='nome',
            field=models.CharField(help_text='Nome completo do responsável técnico', max_length=150),
        ),
    ]
