# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-19 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_cpf_enderecoobra_enderecorequerente_requerente'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlvaraConstrucao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_alvara', models.IntegerField(unique=True)),
                ('ano_alvara', models.IntegerField()),
                ('num_processo', models.CharField(max_length=12)),
                ('area_terreno', models.DecimalField(decimal_places=2, max_digits=10)),
                ('area_construida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('data_alvara', models.DateField()),
                ('endereco_obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.EnderecoObra')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Requerente')),
            ],
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ResponsavelTecnico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_resp_tecnico', models.CharField(max_length=100)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Cargo')),
            ],
        ),
        migrations.AddField(
            model_name='alvaraconstrucao',
            name='resp_tecnico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.ResponsavelTecnico'),
        ),
    ]
