# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-24 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20160927_0004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerScore',
            new_name='Score',
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
