# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-04 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='password123', max_length=16),
        ),
    ]
